package com.example.watchapp.presentation.utils

const val CUSTOM_INTENT_USER_ACTION = "USER-ACTIVITY-DETECTION-INTENT-ACTION"
const val CUSTOM_REQUEST_CODE_USER_ACTION = 1000

const val REQUEST_CODE_ACTIVITY_TRANSITION = 123
const val REQUEST_CODE_INTENT_ACTIVITY_TRANSITION = 122
const val ACTIVITY_TRANSITION_NOTIFICATION_ID = 111
const val ACTIVITY_TRANSITION_STORAGE = "ACTIVITY_TRANSITION_STORAGE"